/**
 * Shared logic for skill discovery, validation, and deterministic
 * generation of agent-specific skill copies. Used by sync-agent-skills.ts
 * (writes) and check-agent-parity.ts (verifies). No symlinks — plain file
 * copies that work on macOS, Linux, Windows, and CI.
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { ROOT, loadYaml, parseFrontmatter } from "./util";

export interface CanonicalSkill {
  name: string;
  description: string;
  /** file paths relative to the skill directory, sorted */
  files: string[];
}

export interface SkillIssue {
  skill: string;
  problem: string;
}

const SKILLS_DIR = "skills";

export const REQUIRED_SKILL_SECTIONS = [
  "## Purpose",
  "## Trigger conditions",
  "## When not to use",
  "## Required inputs",
  "## Documents to read",
  "## Files this skill may change",
  "## Files this skill must not change",
  "## Execution steps",
  "## Hard rules",
  "## Expected output",
  "## Validation",
  "## Failure behaviour",
  "## Human approval boundaries",
] as const;

function listFiles(dir: string, prefix = ""): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir).sort()) {
    const full = join(dir, e);
    const rel = prefix ? `${prefix}/${e}` : e;
    if (statSync(full).isDirectory()) out.push(...listFiles(full, rel));
    else out.push(rel);
  }
  return out;
}

/** Discover canonical skills and structural issues. */
export function discoverSkills(): { skills: CanonicalSkill[]; issues: SkillIssue[] } {
  const skills: CanonicalSkill[] = [];
  const issues: SkillIssue[] = [];
  const base = join(ROOT, SKILLS_DIR);
  if (!existsSync(base)) return { skills, issues: [{ skill: "-", problem: "skills/ missing" }] };

  const seen = new Map<string, string>();
  for (const dir of readdirSync(base).sort()) {
    const full = join(base, dir);
    if (!statSync(full).isDirectory()) continue;
    const skillMd = join(full, "SKILL.md");
    if (!existsSync(skillMd)) {
      issues.push({ skill: dir, problem: "missing SKILL.md" });
      continue;
    }
    const fm = parseFrontmatter(readFileSync(skillMd, "utf8"));
    if (!fm) {
      issues.push({ skill: dir, problem: "SKILL.md has no valid frontmatter" });
      continue;
    }
    const name = String(fm.data.name ?? "");
    const description = String(fm.data.description ?? "");
    if (name !== dir)
      issues.push({ skill: dir, problem: `frontmatter name "${name}" != directory name` });
    if (description.length < 20)
      issues.push({
        skill: dir,
        problem: "description too short for reliable skill selection (<20 chars)",
      });
    if (seen.has(name)) issues.push({ skill: dir, problem: `duplicate skill name "${name}"` });
    seen.set(name, dir);
    skills.push({ name: dir, description, files: listFiles(full) });
  }
  return { skills, issues };
}

/** Validate section structure of a SKILL.md body. */
export function missingSections(skillMd: string): string[] {
  return REQUIRED_SKILL_SECTIONS.filter((s) => !skillMd.includes(`\n${s}`));
}

export type Target = "codex" | "claude";

export const TARGET_DIRS: Record<Target, string> = {
  codex: ".agents/skills",
  claude: ".claude/skills",
};

function generatedMarker(skill: string): string {
  return `<!-- GENERATED FILE - do not edit. Canonical source: skills/${skill}/SKILL.md. Regenerate with: pnpm agents:sync -->`;
}

function markSkillMd(content: string, skill: string): string {
  // Insert the marker immediately after the closing frontmatter fence so
  // the frontmatter stays first (required by agent skill loaders).
  const end = content.indexOf("\n---", 3);
  if (!content.startsWith("---") || end === -1) return `${generatedMarker(skill)}\n\n${content}`;
  const fenceEnd = content.indexOf("\n", end + 1);
  return `${content.slice(0, fenceEnd + 1)}\n${generatedMarker(skill)}\n${content.slice(fenceEnd + 1)}`;
}

function targetReadme(target: Target): string {
  const dir = TARGET_DIRS[target];
  const agent = target === "codex" ? "OpenAI Codex" : "Claude Code";
  return [
    `# Generated skills for ${agent}`,
    "",
    "Every file under this directory is GENERATED from the canonical",
    "skills in `skills/`. Do not edit here — edits are overwritten.",
    "",
    "- Edit the canonical skill: `skills/<name>/SKILL.md`",
    "- Regenerate: `pnpm agents:sync`",
    "- Verify parity: `pnpm agents:check`",
    "",
    `Generated by scripts/sync-agent-skills.ts into \`${dir}/\`.`,
    "",
  ].join("\n");
}

/**
 * Compute the exact expected file tree for a target as a map of
 * target-root-relative path -> content. Deterministic: sorted skills,
 * sorted files, stable marker text.
 */
export function expectedTree(target: Target): Map<string, string> {
  const framework = loadYaml<{
    sync_excludes: Record<Target, string[]>;
  }>("config/framework.yaml");
  const excludes = new Set(framework.sync_excludes[target] ?? []);
  const { skills } = discoverSkills();
  const tree = new Map<string, string>();
  tree.set("README.md", targetReadme(target));
  for (const skill of skills) {
    for (const rel of skill.files) {
      if (excludes.has(rel)) continue;
      const content = readFileSync(join(ROOT, SKILLS_DIR, skill.name, rel), "utf8");
      const finalContent = rel === "SKILL.md" ? markSkillMd(content, skill.name) : content;
      tree.set(`${skill.name}/${rel}`, finalContent);
    }
  }
  return tree;
}

/** List actual files currently present under a target dir. */
export function actualTree(target: Target): Map<string, string> {
  const base = join(ROOT, TARGET_DIRS[target]);
  const tree = new Map<string, string>();
  if (!existsSync(base)) return tree;
  for (const rel of listFiles(base)) tree.set(rel, readFileSync(join(base, rel), "utf8"));
  return tree;
}
